spring:

  messages: Hello World!
  datasource:
    url: jdbc:mysql://localhost:3306/empty_example?useSSL=false&serverTimezone=UTC
    username: sami
    password: 123456
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 8090

